// <auto-generated />
using System;
using Final_VS1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Final_VS1.Migrations
{
    [DbContext(typeof(LittleFishBeautyContext))]
    partial class LittleFishBeautyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChiTietBienThe", b =>
                {
                    b.Property<int>("IdBienThe")
                        .HasColumnType("int")
                        .HasColumnName("ID_BienThe");

                    b.Property<int>("IdGiaTri")
                        .HasColumnType("int")
                        .HasColumnName("ID_GiaTri");

                    b.HasKey("IdBienThe", "IdGiaTri")
                        .HasName("PK__ChiTietB__DB9B181E4D5CE997");

                    b.HasIndex("IdGiaTri");

                    b.ToTable("ChiTietBienThe", (string)null);
                });

            modelBuilder.Entity("Final_VS1.Data.AnhSanPham", b =>
                {
                    b.Property<int>("IdAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Anh");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAnh"));

                    b.Property<string>("DuongDan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("IdSanPham")
                        .HasColumnType("int")
                        .HasColumnName("ID_SanPham");

                    b.Property<string>("LinkCloudinary")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Link_cloudinary");

                    b.Property<string>("LoaiAnh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdAnh")
                        .HasName("PK__AnhSanPh__2A42605DB6412A54");

                    b.HasIndex("IdSanPham");

                    b.ToTable("AnhSanPham", (string)null);
                });

            modelBuilder.Entity("Final_VS1.Data.BienTheSanPham", b =>
                {
                    b.Property<int>("IdBienThe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_BienThe");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBienThe"));

                    b.Property<decimal?>("GiaBan")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("IdSanPham")
                        .HasColumnType("int")
                        .HasColumnName("ID_SanPham");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SKU");

                    b.Property<int?>("SoLuongTonKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("IdBienThe")
                        .HasName("PK__BienTheS__64C29E1002DB15B2");

                    b.HasIndex("IdSanPham");

                    b.HasIndex(new[] { "Sku" }, "UQ__BienTheS__CA1ECF0D4C7809EA")
                        .IsUnique()
                        .HasFilter("[SKU] IS NOT NULL");

                    b.ToTable("BienTheSanPham", (string)null);
                });

            modelBuilder.Entity("Final_VS1.Data.ChatMessage", b =>
                {
                    b.Property<int>("IdChat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Chat");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChat"));

                    b.Property<int>("IdTaiKhoanGui")
                        .HasColumnType("int")
                        .HasColumnName("ID_TaiKhoanGui");

                    b.Property<int>("IdTaiKhoanNhan")
                        .HasColumnType("int")
                        .HasColumnName("ID_TaiKhoanNhan");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdChat")
                        .HasName("PK__ChatMess__73D612B41546D3C9");

                    b.HasIndex("IdTaiKhoanGui");

                    b.HasIndex("IdTaiKhoanNhan");

                    b.ToTable("ChatMessage", (string)null);
                });

            modelBuilder.Entity("Final_VS1.Data.ChiTietDonHang", b =>
                {
                    b.Property<int>("IdChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_ChiTiet");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChiTiet"));

                    b.Property<decimal?>("GiaLucDat")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("IdBienThe")
                        .HasColumnType("int")
                        .HasColumnName("ID_BienThe");

                    b.Property<int?>("IdDonHang")
                        .HasColumnType("int")
                        .HasColumnName("ID_DonHang");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("IdChiTiet")
                        .HasName("PK__ChiTietD__1EF2F705080D8094");

                    b.HasIndex("IdBienThe");

                    b.HasIndex("IdDonHang");

                    b.ToTable("ChiTietDonHang", (string)null);
                });

            modelBuilder.Entity("Final_VS1.Data.ChiTietGioHang", b =>
                {
                    b.Property<int>("IdChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_ChiTiet");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChiTiet"));

                    b.Property<int?>("IdBienThe")
                        .HasColumnType("int")
                        .HasColumnName("ID_BienThe");

                    b.Property<int?>("IdGioHang")
                        .HasColumnType("int")
                        .HasColumnName("ID_GioHang");

                    b.Property<int?>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("IdChiTiet")
                        .HasName("PK__ChiTietG__1EF2F7053769040F");

                    b.HasIndex("IdBienThe");

                    b.HasIndex("IdGioHang");

                    b.ToTable("ChiTietGioHang", (string)null);
                });

            modelBuilder.Entity("Final_VS1.Data.DangNhapGoogle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("GoogleID");

                    b.Property<int>("IdTaiKhoan")
                        .HasColumnType("int")
                        .HasColumnName("ID_TaiKhoan");

                    b.HasKey("Id")
                        .HasName("PK__DangNhap__3214EC277D367A72");

                    b.HasIndex("IdTaiKhoan");

                    b.HasIndex(new[] { "GoogleId" }, "UQ_GoogleID")
                        .IsUnique();

                    b.ToTable("DangNhapGoogle", (string)null);
                });

            modelBuilder.Entity("Final_VS1.Data.DanhGium", b =>
                {
                    b.Property<int>("IdDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_DanhGia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDanhGia"));

                    b.Property<string>("AnhDanhGia")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("BinhLuan")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("IdSanPham")
                        .HasColumnType("int")
                        .HasColumnName("ID_SanPham");

                    b.Property<int?>("IdTaiKhoan")
                        .HasColumnType("int")
                        .HasColumnName("ID_TaiKhoan");

                    b.Property<DateTime?>("NgayDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("NgayTraLoi")
                        .HasColumnType("datetime");

                    b.Property<int?>("SoSao")
                        .HasColumnType("int");

                    b.Property<string>("TraLoiCuaShop")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("IdDanhGia")
                        .HasName("PK__DanhGia__6C898AE152B7D84F");

                    b.HasIndex("IdSanPham");

                    b.HasIndex("IdTaiKhoan");

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("Final_VS1.Data.DanhMuc", b =>
                {
                    b.Property<int>("IdDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_DanhMuc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDanhMuc"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DuongDanSeo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DuongDanSEO");

                    b.Property<int?>("IdDanhMucCha")
                        .HasColumnType("int")
                        .HasColumnName("ID_DanhMucCha");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDanhMuc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ThuTuHienThi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("IdDanhMuc")
                        .HasName("PK__DanhMuc__662ACB0181916410");

                    b.HasIndex("IdDanhMucCha");

                    b.ToTable("DanhMuc", (string)null);
                });

            modelBuilder.Entity("Final_VS1.Data.DiaChi", b =>
                {
                    b.Property<int>("IdDiaChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_DiaChi");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDiaChi"));

                    b.Property<string>("DiaChiChiTiet")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTenNguoiNhan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("IdTaiKhoan")
                        .HasColumnType("int")
                        .HasColumnName("ID_TaiKhoan");

                    b.Property<string>("LoaiDiaChi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("MacDinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdDiaChi")
                        .HasName("PK__DiaChi__C793F2526A4BF583");

                    b.HasIndex("IdTaiKhoan");

                    b.ToTable("DiaChi", (string)null);
                });

            modelBuilder.Entity("Final_VS1.Data.DieuKienKhuyenMai", b =>
                {
                    b.Property<int>("IdDieuKien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_DieuKien");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDieuKien"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GiaTri")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("IdKhuyenMai")
                        .HasColumnType("int")
                        .HasColumnName("ID_KhuyenMai");

                    b.Property<string>("LoaiDieuKien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdDieuKien")
                        .HasName("PK__DieuKien__5E1F2A3B2C4D5E6F");

                    b.HasIndex("IdKhuyenMai");

                    b.ToTable("DieuKienKhuyenMai", (string)null);
                });

            modelBuilder.Entity("Final_VS1.Data.DonHang", b =>
                {
                    b.Property<int>("IdDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_DonHang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDonHang"));

                    b.Property<int?>("IdDiaChi")
                        .HasColumnType("int")
                        .HasColumnName("ID_DiaChi");

                    b.Property<int?>("IdTaiKhoan")
                        .HasColumnType("int")
                        .HasColumnName("ID_TaiKhoan");

                    b.Property<int?>("IdVc")
                        .HasColumnType("int")
                        .HasColumnName("ID_VC");

                    b.Property<DateTime?>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdDonHang")
                        .HasName("PK__DonHang__99B726393BBCC202");

                    b.HasIndex("IdDiaChi");

                    b.HasIndex("IdTaiKhoan");

                    b.HasIndex("IdVc");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("Final_VS1.Data.GiaTriThuocTinh", b =>
                {
                    b.Property<int>("IdGiaTri")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_GiaTri");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGiaTri"));

                    b.Property<string>("GiaTri")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("IdThuocTinh")
                        .HasColumnType("int")
                        .HasColumnName("ID_ThuocTinh");

                    b.HasKey("IdGiaTri")
                        .HasName("PK__GiaTriTh__F59860EAF6E4A059");

                    b.HasIndex("IdThuocTinh");

                    b.ToTable("GiaTriThuocTinh", (string)null);
                });

            modelBuilder.Entity("Final_VS1.Data.GioHang", b =>
                {
                    b.Property<int>("IdGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_GioHang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGioHang"));

                    b.Property<int?>("IdTaiKhoan")
                        .HasColumnType("int")
                        .HasColumnName("ID_TaiKhoan");

                    b.Property<DateTime?>("NgayCapNhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("IdGioHang")
                        .HasName("PK__GioHang__C033AA17120F6D1B");

                    b.HasIndex("IdTaiKhoan");

                    b.ToTable("GioHang", (string)null);
                });

            modelBuilder.Entity("Final_VS1.Data.KhuyenMai", b =>
                {
                    b.Property<int>("IdKhuyenMai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_KhuyenMai");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKhuyenMai"));

                    b.Property<string>("AnhBanner")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("CoTheKetHop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("GiaTriDonHangToiThieu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaTriGiam")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("GiaTriGiamToiDa")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("GiaTriGiamToiDaDonHang")
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeSpan?>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<bool>("HienThiTrangChu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("HinhThucGiam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LoaiKhuyenMai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NgayApDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("NguoiSua")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongDaBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("SoLuongGioiHan")
                        .HasColumnType("int");

                    b.Property<string>("TenKhuyenMai")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("NHAP");

                    b.Property<int>("UuTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("IdKhuyenMai")
                        .HasName("PK__KhuyenMa__8C93C7F9A1B2C3D4");

                    b.HasIndex("NguoiSua");

                    b.HasIndex("NguoiTao");

                    b.ToTable("KhuyenMai", (string)null);
                });

            modelBuilder.Entity("Final_VS1.Data.KhuyenMaiDanhMuc", b =>
                {
                    b.Property<int>("IdKhuyenMai")
                        .HasColumnType("int")
                        .HasColumnName("ID_KhuyenMai");

                    b.Property<int>("IdDanhMuc")
                        .HasColumnType("int")
                        .HasColumnName("ID_DanhMuc");

                    b.Property<bool>("ApDungChoSanPhamCon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("IdKhuyenMai", "IdDanhMuc")
                        .HasName("PK_KhuyenMaiDanhMuc");

                    b.HasIndex("IdDanhMuc");

                    b.ToTable("KhuyenMaiDanhMuc", (string)null);
                });

            modelBuilder.Entity("Final_VS1.Data.KhuyenMaiSanPham", b =>
                {
                    b.Property<int>("IdKhuyenMai")
                        .HasColumnType("int")
                        .HasColumnName("ID_KhuyenMai");

                    b.Property<int>("IdSanPham")
                        .HasColumnType("int")
                        .HasColumnName("ID_SanPham");

                    b.Property<decimal?>("GiaKhuyenMai")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("SoLuongConLai")
                        .HasColumnType("int");

                    b.HasKey("IdKhuyenMai", "IdSanPham")
                        .HasName("PK_KhuyenMaiSanPham");

                    b.HasIndex("IdSanPham");

                    b.ToTable("KhuyenMaiSanPham", (string)null);
                });

            modelBuilder.Entity("Final_VS1.Data.LogHoatDong", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Log");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLog"));

                    b.Property<string>("DoiTuong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("IdDoiTuong")
                        .HasColumnType("int")
                        .HasColumnName("ID_DoiTuong");

                    b.Property<int?>("IdTaiKhoan")
                        .HasColumnType("int")
                        .HasColumnName("ID_TaiKhoan");

                    b.Property<string>("Ip")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IP");

                    b.Property<DateTime?>("ThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("IdLog")
                        .HasName("PK__LogHoatD__2DBF3395A4D898FA");

                    b.HasIndex("IdTaiKhoan");

                    b.ToTable("LogHoatDong", (string)null);
                });

            modelBuilder.Entity("Final_VS1.Data.MailMarketing", b =>
                {
                    b.Property<int>("IdMail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Mail");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMail"));

                    b.Property<DateTime?>("NgayGui")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NhomKhach")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMail")
                        .HasName("PK__MailMark__7E200889DECDC867");

                    b.ToTable("MailMarketing", (string)null);
                });

            modelBuilder.Entity("Final_VS1.Data.PhanHoiDonHang", b =>
                {
                    b.Property<int>("IdPhanHoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_PhanHoi");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPhanHoi"));

                    b.Property<int>("IdDonHang")
                        .HasColumnType("int")
                        .HasColumnName("ID_DonHang");

                    b.Property<DateTime?>("NgayPhanHoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPhanHoi")
                        .HasName("PK__PhanHoiD__8FC78EF09232ACE9");

                    b.HasIndex("IdDonHang");

                    b.ToTable("PhanHoiDonHang", (string)null);
                });

            modelBuilder.Entity("Final_VS1.Data.PhuongThucVanChuyen", b =>
                {
                    b.Property<int>("IdVc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_VC");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVc"));

                    b.Property<string>("Apikey")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("APIKey");

                    b.Property<decimal?>("PhiVc")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("PhiVC");

                    b.Property<string>("TenVc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenVC");

                    b.Property<bool?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("IdVc")
                        .HasName("PK__PhuongTh__8B63A17E5AEF7C9E");

                    b.ToTable("PhuongThucVanChuyen", (string)null);
                });

            modelBuilder.Entity("Final_VS1.Data.SanPham", b =>
                {
                    b.Property<int>("IdSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_SanPham");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSanPham"));

                    b.Property<string>("CachSuDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdDanhMuc")
                        .HasColumnType("int")
                        .HasColumnName("ID_DanhMuc");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenSanPham")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("IdSanPham")
                        .HasName("PK__SanPham__617EA392FAC14B56");

                    b.HasIndex("IdDanhMuc");

                    b.HasIndex(new[] { "Slug" }, "IX_SanPham_Slug")
                        .IsUnique()
                        .HasFilter("[Slug] IS NOT NULL");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("Final_VS1.Data.SubscribeEmail", b =>
                {
                    b.Property<int>("IdSub")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Sub");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSub"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("IdSub")
                        .HasName("PK__Subscrib__27F89E889373045E");

                    b.HasIndex(new[] { "Email" }, "UQ_SubscribeEmail")
                        .IsUnique();

                    b.ToTable("SubscribeEmail", (string)null);
                });

            modelBuilder.Entity("Final_VS1.Data.TaiKhoan", b =>
                {
                    b.Property<int>("IdTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_TaiKhoan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTaiKhoan"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("NhanEmailMarketing")
                        .HasColumnType("bit");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("VaiTro")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdTaiKhoan")
                        .HasName("PK__TaiKhoan__0E3EC21049DC8528");

                    b.HasIndex(new[] { "Email" }, "UQ__TaiKhoan__A9D1053483FC35CB")
                        .IsUnique();

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("Final_VS1.Data.ThanhPhan", b =>
                {
                    b.Property<int>("IdThanhPhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_ThanhPhan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdThanhPhan"));

                    b.Property<string>("TenThanhPhan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdThanhPhan")
                        .HasName("PK__ThanhPha__3E6E2D52F90FD5EF");

                    b.ToTable("ThanhPhan", (string)null);
                });

            modelBuilder.Entity("Final_VS1.Data.ThanhToan", b =>
                {
                    b.Property<int>("IdThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_ThanhToan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdThanhToan"));

                    b.Property<int>("IdDonHang")
                        .HasColumnType("int")
                        .HasColumnName("ID_DonHang");

                    b.Property<string>("MaGiaoDichNganHang")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MaNganHang")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MaPhanHoi")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiDungThanhToan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("ThoiGianThanhToan")
                        .HasColumnType("datetime");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdThanhToan")
                        .HasName("PK__ThanhToa__AB2E5631DD215677");

                    b.HasIndex(new[] { "IdDonHang" }, "IX_ThanhToan_ID_DonHang");

                    b.HasIndex(new[] { "MaGiaoDichNganHang" }, "IX_ThanhToan_MaGiaoDichNganHang");

                    b.ToTable("ThanhToan", (string)null);
                });

            modelBuilder.Entity("Final_VS1.Data.ThuocTinh", b =>
                {
                    b.Property<int>("IdThuocTinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_ThuocTinh");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdThuocTinh"));

                    b.Property<string>("TenThuocTinh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdThuocTinh")
                        .HasName("PK__ThuocTin__C49F0885BDC97067");

                    b.ToTable("ThuocTinh", (string)null);
                });

            modelBuilder.Entity("Final_VS1.Data.TimelineDonHang", b =>
                {
                    b.Property<int>("IdTimeline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Timeline");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTimeline"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IdDonHang")
                        .HasColumnType("int")
                        .HasColumnName("ID_DonHang");

                    b.Property<DateTime?>("NgayCapNhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TrangThaiMoi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTimeline")
                        .HasName("PK__Timeline__5CF3344F4121B211");

                    b.HasIndex("IdDonHang");

                    b.ToTable("TimelineDonHang", (string)null);
                });

            modelBuilder.Entity("SanPhamThanhPhan", b =>
                {
                    b.Property<int>("IdSanPham")
                        .HasColumnType("int")
                        .HasColumnName("ID_SanPham");

                    b.Property<int>("IdThanhPhan")
                        .HasColumnType("int")
                        .HasColumnName("ID_ThanhPhan");

                    b.HasKey("IdSanPham", "IdThanhPhan")
                        .HasName("PK__SanPham___52984147E7616660");

                    b.HasIndex("IdThanhPhan");

                    b.ToTable("SanPham_ThanhPhan", (string)null);
                });

            modelBuilder.Entity("ChiTietBienThe", b =>
                {
                    b.HasOne("Final_VS1.Data.BienTheSanPham", null)
                        .WithMany()
                        .HasForeignKey("IdBienThe")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietBi__ID_Bi__7C4F7684");

                    b.HasOne("Final_VS1.Data.GiaTriThuocTinh", null)
                        .WithMany()
                        .HasForeignKey("IdGiaTri")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietBi__ID_Gi__7D439ABD");
                });

            modelBuilder.Entity("Final_VS1.Data.AnhSanPham", b =>
                {
                    b.HasOne("Final_VS1.Data.SanPham", "IdSanPhamNavigation")
                        .WithMany("AnhSanPhams")
                        .HasForeignKey("IdSanPham")
                        .HasConstraintName("FK__AnhSanPha__ID_Sa__787EE5A0");

                    b.Navigation("IdSanPhamNavigation");
                });

            modelBuilder.Entity("Final_VS1.Data.BienTheSanPham", b =>
                {
                    b.HasOne("Final_VS1.Data.SanPham", "IdSanPhamNavigation")
                        .WithMany("BienTheSanPhams")
                        .HasForeignKey("IdSanPham")
                        .HasConstraintName("FK__BienTheSa__ID_Sa__797309D9");

                    b.Navigation("IdSanPhamNavigation");
                });

            modelBuilder.Entity("Final_VS1.Data.ChatMessage", b =>
                {
                    b.HasOne("Final_VS1.Data.TaiKhoan", "IdTaiKhoanGuiNavigation")
                        .WithMany("ChatMessageIdTaiKhoanGuiNavigations")
                        .HasForeignKey("IdTaiKhoanGui")
                        .IsRequired()
                        .HasConstraintName("FK_ChatMessage_TaiKhoanGui");

                    b.HasOne("Final_VS1.Data.TaiKhoan", "IdTaiKhoanNhanNavigation")
                        .WithMany("ChatMessageIdTaiKhoanNhanNavigations")
                        .HasForeignKey("IdTaiKhoanNhan")
                        .IsRequired()
                        .HasConstraintName("FK_ChatMessage_TaiKhoanNhan");

                    b.Navigation("IdTaiKhoanGuiNavigation");

                    b.Navigation("IdTaiKhoanNhanNavigation");
                });

            modelBuilder.Entity("Final_VS1.Data.ChiTietDonHang", b =>
                {
                    b.HasOne("Final_VS1.Data.BienTheSanPham", "IdBienTheNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("IdBienThe")
                        .HasConstraintName("FK__ChiTietDo__ID_Bi__7E37BEF6");

                    b.HasOne("Final_VS1.Data.DonHang", "IdDonHangNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("IdDonHang")
                        .HasConstraintName("FK__ChiTietDo__ID_Do__7F2BE32F");

                    b.Navigation("IdBienTheNavigation");

                    b.Navigation("IdDonHangNavigation");
                });

            modelBuilder.Entity("Final_VS1.Data.ChiTietGioHang", b =>
                {
                    b.HasOne("Final_VS1.Data.BienTheSanPham", "IdBienTheNavigation")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("IdBienThe")
                        .HasConstraintName("FK__ChiTietGi__ID_Bi__00200768");

                    b.HasOne("Final_VS1.Data.GioHang", "IdGioHangNavigation")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("IdGioHang")
                        .HasConstraintName("FK__ChiTietGi__ID_Gi__01142BA1");

                    b.Navigation("IdBienTheNavigation");

                    b.Navigation("IdGioHangNavigation");
                });

            modelBuilder.Entity("Final_VS1.Data.DangNhapGoogle", b =>
                {
                    b.HasOne("Final_VS1.Data.TaiKhoan", "IdTaiKhoanNavigation")
                        .WithMany("DangNhapGoogles")
                        .HasForeignKey("IdTaiKhoan")
                        .IsRequired()
                        .HasConstraintName("FK_DangNhapGoogle_TaiKhoan");

                    b.Navigation("IdTaiKhoanNavigation");
                });

            modelBuilder.Entity("Final_VS1.Data.DanhGium", b =>
                {
                    b.HasOne("Final_VS1.Data.SanPham", "IdSanPhamNavigation")
                        .WithMany("DanhGia")
                        .HasForeignKey("IdSanPham")
                        .HasConstraintName("FK__DanhGia__ID_SanP__02FC7413");

                    b.HasOne("Final_VS1.Data.TaiKhoan", "IdTaiKhoanNavigation")
                        .WithMany("DanhGia")
                        .HasForeignKey("IdTaiKhoan")
                        .HasConstraintName("FK__DanhGia__ID_TaiK__03F0984C");

                    b.Navigation("IdSanPhamNavigation");

                    b.Navigation("IdTaiKhoanNavigation");
                });

            modelBuilder.Entity("Final_VS1.Data.DanhMuc", b =>
                {
                    b.HasOne("Final_VS1.Data.DanhMuc", "IdDanhMucChaNavigation")
                        .WithMany("InverseIdDanhMucChaNavigation")
                        .HasForeignKey("IdDanhMucCha")
                        .HasConstraintName("FK__DanhMuc__ID_Danh__04E4BC85");

                    b.Navigation("IdDanhMucChaNavigation");
                });

            modelBuilder.Entity("Final_VS1.Data.DiaChi", b =>
                {
                    b.HasOne("Final_VS1.Data.TaiKhoan", "IdTaiKhoanNavigation")
                        .WithMany("DiaChis")
                        .HasForeignKey("IdTaiKhoan")
                        .HasConstraintName("FK__DiaChi__ID_TaiKh__05D8E0BE");

                    b.Navigation("IdTaiKhoanNavigation");
                });

            modelBuilder.Entity("Final_VS1.Data.DieuKienKhuyenMai", b =>
                {
                    b.HasOne("Final_VS1.Data.KhuyenMai", "IdKhuyenMaiNavigation")
                        .WithMany("DieuKienKhuyenMais")
                        .HasForeignKey("IdKhuyenMai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DieuKienKhuyenMai_KhuyenMai");

                    b.Navigation("IdKhuyenMaiNavigation");
                });

            modelBuilder.Entity("Final_VS1.Data.DonHang", b =>
                {
                    b.HasOne("Final_VS1.Data.DiaChi", "IdDiaChiNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("IdDiaChi")
                        .HasConstraintName("FK__DonHang__ID_DiaC__06CD04F7");

                    b.HasOne("Final_VS1.Data.TaiKhoan", "IdTaiKhoanNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("IdTaiKhoan")
                        .HasConstraintName("FK__DonHang__ID_TaiK__07C12930");

                    b.HasOne("Final_VS1.Data.PhuongThucVanChuyen", "IdVcNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("IdVc")
                        .HasConstraintName("FK_DonHang_PhuongThucVanChuyen");

                    b.Navigation("IdDiaChiNavigation");

                    b.Navigation("IdTaiKhoanNavigation");

                    b.Navigation("IdVcNavigation");
                });

            modelBuilder.Entity("Final_VS1.Data.GiaTriThuocTinh", b =>
                {
                    b.HasOne("Final_VS1.Data.ThuocTinh", "IdThuocTinhNavigation")
                        .WithMany("GiaTriThuocTinhs")
                        .HasForeignKey("IdThuocTinh")
                        .HasConstraintName("FK__GiaTriThu__ID_Th__09A971A2");

                    b.Navigation("IdThuocTinhNavigation");
                });

            modelBuilder.Entity("Final_VS1.Data.GioHang", b =>
                {
                    b.HasOne("Final_VS1.Data.TaiKhoan", "IdTaiKhoanNavigation")
                        .WithMany("GioHangs")
                        .HasForeignKey("IdTaiKhoan")
                        .HasConstraintName("FK__GioHang__ID_TaiK__0A9D95DB");

                    b.Navigation("IdTaiKhoanNavigation");
                });

            modelBuilder.Entity("Final_VS1.Data.KhuyenMai", b =>
                {
                    b.HasOne("Final_VS1.Data.TaiKhoan", "NguoiSuaNavigation")
                        .WithMany()
                        .HasForeignKey("NguoiSua")
                        .HasConstraintName("FK_KhuyenMai_NguoiSua");

                    b.HasOne("Final_VS1.Data.TaiKhoan", "NguoiTaoNavigation")
                        .WithMany()
                        .HasForeignKey("NguoiTao")
                        .HasConstraintName("FK_KhuyenMai_NguoiTao");

                    b.Navigation("NguoiSuaNavigation");

                    b.Navigation("NguoiTaoNavigation");
                });

            modelBuilder.Entity("Final_VS1.Data.KhuyenMaiDanhMuc", b =>
                {
                    b.HasOne("Final_VS1.Data.DanhMuc", "IdDanhMucNavigation")
                        .WithMany()
                        .HasForeignKey("IdDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KhuyenMaiDanhMuc_DanhMuc");

                    b.HasOne("Final_VS1.Data.KhuyenMai", "IdKhuyenMaiNavigation")
                        .WithMany("KhuyenMaiDanhMucs")
                        .HasForeignKey("IdKhuyenMai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KhuyenMaiDanhMuc_KhuyenMai");

                    b.Navigation("IdDanhMucNavigation");

                    b.Navigation("IdKhuyenMaiNavigation");
                });

            modelBuilder.Entity("Final_VS1.Data.KhuyenMaiSanPham", b =>
                {
                    b.HasOne("Final_VS1.Data.KhuyenMai", "IdKhuyenMaiNavigation")
                        .WithMany("KhuyenMaiSanPhams")
                        .HasForeignKey("IdKhuyenMai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KhuyenMaiSanPham_KhuyenMai");

                    b.HasOne("Final_VS1.Data.SanPham", "IdSanPhamNavigation")
                        .WithMany()
                        .HasForeignKey("IdSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KhuyenMaiSanPham_SanPham");

                    b.Navigation("IdKhuyenMaiNavigation");

                    b.Navigation("IdSanPhamNavigation");
                });

            modelBuilder.Entity("Final_VS1.Data.LogHoatDong", b =>
                {
                    b.HasOne("Final_VS1.Data.TaiKhoan", "IdTaiKhoanNavigation")
                        .WithMany("LogHoatDongs")
                        .HasForeignKey("IdTaiKhoan")
                        .HasConstraintName("FK_LogHoatDong_TaiKhoan");

                    b.Navigation("IdTaiKhoanNavigation");
                });

            modelBuilder.Entity("Final_VS1.Data.PhanHoiDonHang", b =>
                {
                    b.HasOne("Final_VS1.Data.DonHang", "IdDonHangNavigation")
                        .WithMany("PhanHoiDonHangs")
                        .HasForeignKey("IdDonHang")
                        .IsRequired()
                        .HasConstraintName("FK_PhanHoiDonHang_DonHang");

                    b.Navigation("IdDonHangNavigation");
                });

            modelBuilder.Entity("Final_VS1.Data.SanPham", b =>
                {
                    b.HasOne("Final_VS1.Data.DanhMuc", "IdDanhMucNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdDanhMuc")
                        .HasConstraintName("FK__SanPham__ID_Danh__0D7A0286");

                    b.Navigation("IdDanhMucNavigation");
                });

            modelBuilder.Entity("Final_VS1.Data.ThanhToan", b =>
                {
                    b.HasOne("Final_VS1.Data.DonHang", "IdDonHangNavigation")
                        .WithMany("ThanhToans")
                        .HasForeignKey("IdDonHang")
                        .IsRequired()
                        .HasConstraintName("FK_ThanhToan_DonHang");

                    b.Navigation("IdDonHangNavigation");
                });

            modelBuilder.Entity("Final_VS1.Data.TimelineDonHang", b =>
                {
                    b.HasOne("Final_VS1.Data.DonHang", "IdDonHangNavigation")
                        .WithMany("TimelineDonHangs")
                        .HasForeignKey("IdDonHang")
                        .IsRequired()
                        .HasConstraintName("FK_TimelineDonHang_DonHang");

                    b.Navigation("IdDonHangNavigation");
                });

            modelBuilder.Entity("SanPhamThanhPhan", b =>
                {
                    b.HasOne("Final_VS1.Data.SanPham", null)
                        .WithMany()
                        .HasForeignKey("IdSanPham")
                        .IsRequired()
                        .HasConstraintName("FK__SanPham_T__ID_Sa__0E6E26BF");

                    b.HasOne("Final_VS1.Data.ThanhPhan", null)
                        .WithMany()
                        .HasForeignKey("IdThanhPhan")
                        .IsRequired()
                        .HasConstraintName("FK__SanPham_T__ID_Th__0F624AF8");
                });

            modelBuilder.Entity("Final_VS1.Data.BienTheSanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("Final_VS1.Data.DanhMuc", b =>
                {
                    b.Navigation("InverseIdDanhMucChaNavigation");

                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("Final_VS1.Data.DiaChi", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("Final_VS1.Data.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("PhanHoiDonHangs");

                    b.Navigation("ThanhToans");

                    b.Navigation("TimelineDonHangs");
                });

            modelBuilder.Entity("Final_VS1.Data.GioHang", b =>
                {
                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("Final_VS1.Data.KhuyenMai", b =>
                {
                    b.Navigation("DieuKienKhuyenMais");

                    b.Navigation("KhuyenMaiDanhMucs");

                    b.Navigation("KhuyenMaiSanPhams");
                });

            modelBuilder.Entity("Final_VS1.Data.PhuongThucVanChuyen", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("Final_VS1.Data.SanPham", b =>
                {
                    b.Navigation("AnhSanPhams");

                    b.Navigation("BienTheSanPhams");

                    b.Navigation("DanhGia");
                });

            modelBuilder.Entity("Final_VS1.Data.TaiKhoan", b =>
                {
                    b.Navigation("ChatMessageIdTaiKhoanGuiNavigations");

                    b.Navigation("ChatMessageIdTaiKhoanNhanNavigations");

                    b.Navigation("DangNhapGoogles");

                    b.Navigation("DanhGia");

                    b.Navigation("DiaChis");

                    b.Navigation("DonHangs");

                    b.Navigation("GioHangs");

                    b.Navigation("LogHoatDongs");
                });

            modelBuilder.Entity("Final_VS1.Data.ThuocTinh", b =>
                {
                    b.Navigation("GiaTriThuocTinhs");
                });
#pragma warning restore 612, 618
        }
    }
}
